DROP DATABASE IF EXISTS DTHW;
CREATE DATABASE DTHW;
USE DTHW;


CREATE TABLE CARTADICREDITO (
	NCARTA CHAR(12)  PRIMARY KEY,
    SCADENZA TIMESTAMP,
    CVV INT NOT NULL
    );
    
 CREATE TABLE ORDINE (
	ID INT PRIMARY KEY,
    SCONTO INT,
    TOTALE DOUBLE NOT NULL
    );
 
CREATE TABLE CLIENTE (
	USERNAME VARCHAR(30) PRIMARY KEY,
	EMAIL VARCHAR(320)  UNIQUE NOT NULL,
    PASSW VARBINARY(100) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    COGNOME VARCHAR(30) NOT NULL,
    NTELEFONO CHAR(10) NOT NULL,
    DATAACQUISTO TIMESTAMP,
	NCARTA CHAR(12),
	IDORDINE INT,
	FOREIGN KEY (NCARTA) REFERENCES CARTADICREDITO (NCARTA),
    FOREIGN KEY (IDORDINE) REFERENCES ORDINE (ID)
    );

 CREATE TABLE INDIRIZZO (
	VIA VARCHAR(50) UNIQUE NOT NULL,
    NCIVICO INT UNIQUE NOT NULL,
    CITTA VARCHAR (20) NOT NULL,
    CAP INT NOT NULL,
    FLAG BOOLEAN,
    USERNAME VARCHAR(30),
	FOREIGN KEY (USERNAME) REFERENCES CLIENTE (USERNAME),
    PRIMARY KEY (USERNAME,VIA,NCIVICO)
    );


 CREATE TABLE RISIEDE (
	USERNAME VARCHAR(30),
	VIA VARCHAR(50) NOT NULL,
    NCIVICO INT NOT NULL,
	FOREIGN KEY (USERNAME) REFERENCES CLIENTE (USERNAME),
	FOREIGN KEY (VIA) REFERENCES INDIRIZZO (VIA),
	FOREIGN KEY (NCIVICO) REFERENCES INDIRIZZO (NCIVICO)
    );

CREATE TABLE PRODOTTO (
	CODICEBARRE INT PRIMARY KEY,
    PREZZO DOUBLE NOT NULL,
    DESCRIZIONE VARCHAR(1000),
    SPECIFICHE VARCHAR(1000) NOT NULL,
    QUANTITA INT NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    MODELLO VARCHAR(50) NOT NULL
    );
    
CREATE TABLE COMPONE (
	NPRODOTTI INT NOT NULL,
    ID INT,
	CODICEBARRE INT,
	FOREIGN KEY (ID) REFERENCES ORDINE (ID),
	FOREIGN KEY (CODICEBARRE) REFERENCES PRODOTTO (CODICEBARRE)
    );


CREATE TABLE CATEGORIA (
	NOME VARCHAR(50) NOT NULL,
    QUANTITA INT NOT NULL,
	CODICEBARRE INT,
	FOREIGN KEY (CODICEBARRE) REFERENCES PRODOTTO (CODICEBARRE),
    PRIMARY KEY (NOME,CODICEBARRE)
    );



    
    
    