
INSERT INTO CARTADICREDITO VALUES
	("000",NOW(),"26");



INSERT INTO CLIENTE (USERNAME,EMAIL,PASSW,NOME,COGNOME,NTELEFONO) VALUES
	("admin00","admin00@admin.com", SHA1('admin'),"admin","admin","000");

